name: "E2E"

on:
  push:
    paths-ignore:
      - "**.md"
      - 'docs/**'
    # Prevent duplicating jobs on PR-s from local branches
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.md"
      - 'docs/**'

jobs:
  integration-tests:
    name: "Test with ${{ matrix.repository }} on PHP ${{ matrix.php-version }}"

    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            repository: monicahq/chandler
            ref: f57c49400dfa419e78bad240f018bce2949dcac2
            php-version: "8.1"
          -
            repository: koel/koel
            ref: 22946a6413546a1c97ddf7bb4f5254bc6d129dd7
            php-version: "8.1"
          -
            repository: canvural/larastan-test
            ref: 686828b76a2e300b1a3cc99fdd8be9af3a3e7e60
            php-version: "8.1"
          -
            repository: canvural/larastan-strict-rules
            ref: 16ceaa41a54aacc5481d957dd625590e6acd321c
            php-version: "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          path: "larastan"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Checkout dependent repo"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ matrix.repository }}"
          ref: "${{ matrix.ref }}"
          path: "e2e"

      - name: "Install dependencies"
        run: |
          cd e2e/
          composer install --no-scripts --no-interaction
          composer config repositories.0 '{ "type": "path", "url": "../larastan" }'
          composer config minimum-stability dev
          composer require --dev --update-with-all-dependencies "nunomaduro/larastan:*"

      - name: "Perform static analysis"
        working-directory: "e2e"
        env:
          REPOSITORY: "${{ matrix.repository }}"
        run: |
          composer exec -- phpstan analyse -- -c "../larastan/e2e/${REPOSITORY/\//-}.neon"
